apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c60rjgeti-python
  janus-idp.io/tekton: c60rjgeti-python
  backstage.io/kubernetes-id: c60rjgeti-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c60rjgeti-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
